version: '3'

services:
  auditx:
    build: .
    container_name: auditx-app
    restart: always
    ports:
      - "3000:3000"  # 前端端口
      - "3001:3001"  # PDF API端口
    environment:
      - NODE_ENV=production
      - PDF_SERVER_PORT=3001
      - ALLOWED_ORIGINS=https://yourdomain.com
    # 为Puppeteer提供额外的内存
    deploy:
      resources:
        limits:
          memory: 2G 